import CookieConsentModal from "@/components/CookieConsentModal";
import Footer from "@/components/Footer";
import { FloatingNav } from "@/components/Nav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Morgana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-black">
      <body className={inter.className}>
        <ToastProvider>
          <FloatingNav />
          {children}
          <Footer />
          <CookieConsentModal />
        </ToastProvider>
      </body>
    </html>
  );
}
